// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20220318193258_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ENTITIES.Bank", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankCode");

                    b.Property<string>("BankName")
                        .HasMaxLength(100);

                    b.Property<int>("BinCode");

                    b.Property<string>("CardType")
                        .HasMaxLength(5);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCommercialCard");

                    b.Property<bool>("IsSupportInstallment");

                    b.Property<string>("Organization")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("ENTITIES.Payment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("CCV")
                        .HasMaxLength(3);

                    b.Property<string>("CreditCardHolder")
                        .HasMaxLength(10);

                    b.Property<int>("CreditCardNumber");

                    b.Property<string>("Owner")
                        .HasMaxLength(70);

                    b.HasKey("ID");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
